export const listaGiustificativi = {
    " ": "Annulla Assenza ",
    "A": "Aspettativa per Motivi Personali - art. 22 comma 1 DPR 7/2008 e smi",
    "BO": "Banca Ore",
    "MAT": "Congedo Maternità",
    "CO": "Congedo Ordinario",
    "DL119": "Congedo Ordinario per Cure Lavoratori Invalidi - DL 119/2011",
    "CS42": "Congedo Straordinario per Gravi Motivi EX ART. 42",
    "CS151": "Congedo Straordinario D.L.VO 151/2001",
    "legge 104": "L.5 febbraio 1992, n. 104",
    "M": "Malattia",
    "MB": "Malattia Bambino",
    "MCS": "Malattia Causa di Servizio",
    "MH": "Malattia per Day Hospital",
    "MI": "Malattia per Infortunio sul Lavoro",
    "MR": "Malattia per Ricovero Ospedaliero",
    "MV": "Malattia per Visita",
    "PT": "Part Time",
    "P937": "Permesso L. 937/77 (EX FF.SS.)",
    "PM": "Permesso Visita Medica - art. 35 - 18 ore annue",
    "PTT": "Permesso per Testimonianza per Fatti Inerenti al Servizio",
    "PR": "Permesso Retribuito - art. 32",
    "P278": "Permesso Retribuito - DPCM 278/2000",
    "PE": "Permesso Retribuito per Esami",
    "PL": "Permesso Retribuito per Lutto",
    "RC": "Riposo Compensativo",
    "SFS": "Servizio Fuori Sede",
    "SW": "Smart Working",
    "TE": "Terapia"
  };